version: "3"
services:
  java-testapp:     
    build: ./Java-testapp 
    ports:
      - "8080:8080"  
    container_name: Java-app

  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome-debug
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
    container_name: selenium-chrome
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5901:5900"
  
  firefox:
    image: selenium/node-firefox-debug
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
    container_name: selenium-firefox
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5900:5900"

